"use client";

import Link from "next/link";
import { useState } from "react";
import dynamic from "next/dynamic";
import Navbar from "../Navigation/NavBar";
import Footer from "../Navigation/Footer";
import PixelBlast from "@/components/PixelBlast"
import {ProjectModal,ProjectCard} from "@/components/custom/projectViewers"



// Dynamically import the 3D Viewer to prevent Server-Side Rendering (SSR) window errors
const ModelViewer = dynamic(() => import("@/components/custom/ModelViewer"), { ssr: false });

/* =====================
  PROJECT TYPE & DATA
===================== */
type Project = {
  image: string;
  title: string;
  description: string;
  githubLink?: string;
  deployedLink?: string;
  modelPath?: string; // Added optional property for 3D models
};

const projectsData: Project[] = [
  {
    image: "/solespania.png",
    title: "SolEspania — Spain Tour Guide",
    description: "A comprehensive web application designed to guide tourists through Spain. Features interactive guides, location details, and a beautiful UI.",
    deployedLink: "https://spain-tour-guide.vercel.app/",
    githubLink: "https://github.com/Cyberbee-pro/Spain-tour-guide",
  },
  {
    image: "/brain.jpg",
    title: "Brain 3D Model (Blender)",
    description: "A detailed 3D model of a human brain created using Blender. You can interact with this model right here in the browser!",
    modelPath: "/brain.glb", // Triggers the 3D viewer in the modal
  },
  {
    image: "/Synthflow.svg",
    title: "Synthflow — Work in Progress",
    description: "SynthFlow is a lightweight, open-source music streaming platform designed to give the music back to the listener. Inspired by the leek aesthetic, it offers a seamless, high-fidelity audio experience completely free from ad interruptions. ",
    githubLink: "https://github.com/Cyberbee-pro/SynthFlow",
  },
  {
    image: "/Angelplayer.png",
    title: "Angel Player — Work in Progress",
    description: "An anti-doom scrolling browser extension designed to help users manage their screen time and build healthier digital habits.",
    githubLink: "https://github.com/Cyberbee-pro/anti-doom-scroll-extension-",
  },
  {
    image: "/Hackclock.svg",
    title: "HackClock",
    description: "hackTime is a hackathon control room for organizers, stage screens, and participants. It lets you create a timed event flow, launch a live countdown, broadcast announcements, and share a room code so teams can join the clock view instantly.",
    deployedLink: "https://hacktime.githubsrmist.in/",
    githubLink: "https://github.com/SRM-IST-KTR/hacktime",
  },
  {
    image: "/projMedia/morse.jpg",
    title: "M2C - prgraming language",
    description: "M2C is a Morse-code-flavored compiler project whose long-term goal is to translate .cym2c source files into valid English output, currently it has print functionality and main functionalities. ",
    githubLink: "https://github.com/Cyberbee-pro/M2C-compiler",
  },
  {
    image: "/Cpro.png",
    title: "Beedots — Work in Progress",
    description: "A hyprland based arch rice.",
  },
  {
    image: "/Cpro.png",
    title: "AI or Real — Image Authenticator",
    description: "A machine learning based tool designed to authenticate images and detect whether they were generated by AI or captured by a real camera.",
  },
  {
    image: "/Cpro.png",
    title: "Crop Yield Predictor AI",
    description: "An AI-powered application that analyzes agricultural data to predict crop yields, helping farmers optimize their harvests.",
  },
];

export default function Home() {
  return (
    <div className="min-h-screen flex flex-col text-white font-sans">
      <div className="fixed inset-0 z-0 pointer-events-none">
        <PixelBlast
          variant="circle"
          pixelSize={3}
          color="#B497CF"
          patternScale={8}
          patternDensity={1.05}
          pixelSizeJitter={1.6}
          enableRipples
          rippleSpeed={0.4}
          rippleThickness={0.12}
          rippleIntensityScale={1.5}
          liquid={false}
          liquidStrength={0.12}
          liquidRadius={1.2}
          liquidWobbleSpeed={5}
          speed={1.3}
          edgeFade={0.33}
          transparent
          className=""
          style={{}}
        />
      </div>

      {/* FOREGROUND CONTENT LAYER */}
      <div className="relative z-10 flex flex-col min-h-screen">
        <Navbar />
        <Content />
        <Footer />
      </div>
    </div>
  );
}

/* =====================
  CONTENT
===================== */
const Content = () => {
  const [selectedProject, setSelectedProject] = useState<Project | null>(null);

  return (
    <main className="pt-32 flex-1">
      {/* TITLE SECTION */}
      <section className="max-w-7xl mx-auto px-6 md:px-12 mb-12">
        <h1 className="text-6xl md:text-8xl font-bold tracking-widest opacity-90">
          Portfolio
        </h1>
        <div className="h-1 w-24 bg-purple-500 mt-4 rounded-full"></div>
      </section>

      {/* PROJECT GRID */}
      <section className="max-w-7xl mx-auto px-6 md:px-12 pb-24">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8 lg:gap-12">
          {projectsData.map((project, index) => (
            <ProjectCard
              key={index}
              image={project.image}
              title={project.title}
              onClick={() => setSelectedProject(project)}
            />
          ))}
        </div>
      </section>

      {/* MODAL POPUP */}
      {selectedProject && (
        <ProjectModal
          project={selectedProject}
          onClose={() => setSelectedProject(null)}
        />
      )}
    </main>
  );
};
