"use client";

import Link from "next/link";
import { useState } from "react";
import dynamic from "next/dynamic";
import Navbar from "../Navigation/NavBar";
import Footer from "../Navigation/Footer";

// Dynamically import the 3D Viewer to prevent Server-Side Rendering (SSR) window errors
const ModelViewer = dynamic(() => import("../components/ModelViewer"), { ssr: false });

/* =====================
  PROJECT TYPE & DATA
===================== */
type Project = {
  image: string;
  title: string;
  description: string;
  githubLink?: string;
  deployedLink?: string;
  modelPath?: string; // Added optional property for 3D models
};

const projectsData: Project[] = [
  {
    image: "/solespania.png",
    title: "SolEspania — Spain Tour Guide",
    description: "A comprehensive web application designed to guide tourists through Spain. Features interactive guides, location details, and a beautiful UI.",
    deployedLink: "https://spain-tour-guide.vercel.app/",
    githubLink: "https://github.com/Cyberbee-pro/Spain-tour-guide",
  },
  {
    image: "/brain.jpg",
    title: "Brain 3D Model (Blender)",
    description: "A detailed 3D model of a human brain created using Blender. You can interact with this model right here in the browser!",
    modelPath: "/brain.glb", // Triggers the 3D viewer in the modal
  },
  {
    image: "/Synthflow.svg",
    title: "Synthflow — Work in Progress",
    description: "SynthFlow is a lightweight, open-source music streaming platform designed to give the music back to the listener. Inspired by the leek aesthetic, it offers a seamless, high-fidelity audio experience completely free from ad interruptions. ",
    githubLink: "https://github.com/Cyberbee-pro/SynthFlow",
  },
  {
    image: "/Angelplayer.png",
    title: "Angel Player — Work in Progress",
    description: "An anti-doom scrolling browser extension designed to help users manage their screen time and build healthier digital habits.",
    githubLink: "https://github.com/Cyberbee-pro/anti-doom-scroll-extension-",
  },
  {
    image: "/Hackclock.svg",
    title: "HackClock",
    description: "hackTime is a hackathon control room for organizers, stage screens, and participants. It lets you create a timed event flow, launch a live countdown, broadcast announcements, and share a room code so teams can join the clock view instantly.",
    deployedLink: "https://hackclock.vercel.app/",
    githubLink: "https://github.com/SRM-IST-KTR/hacktime",
  },
  {
    image: "/Cpro.png",
    title: "Beedots — Work in Progress",
    description: "A hyprland based arch rice.",
  },
  {
    image: "/Cpro.png",
    title: "AI or Real — Image Authenticator",
    description: "A machine learning based tool designed to authenticate images and detect whether they were generated by AI or captured by a real camera.",
  },
  {
    image: "/Cpro.png",
    title: "Crop Yield Predictor AI",
    description: "An AI-powered application that analyzes agricultural data to predict crop yields, helping farmers optimize their harvests.",
  },
];

export default function Home() {
  return (
    <div className="min-h-screen flex flex-col bg-gradient-to-b from-[#35014d] via-[#1a0029] to-[#1d022a] text-white font-sans">
      <Navbar />
      <Content />
      <Footer />
    </div>
  );
}

/* =====================
  CONTENT
===================== */
const Content = () => {
  const [selectedProject, setSelectedProject] = useState<Project | null>(null);

  return (
    <main className="pt-32 flex-1">
      {/* TITLE SECTION */}
      <section className="max-w-7xl mx-auto px-6 md:px-12 mb-12">
        <h1 className="text-6xl md:text-8xl font-bold tracking-widest opacity-90">
          Portfolio
        </h1>
        <div className="h-1 w-24 bg-purple-500 mt-4 rounded-full"></div>
      </section>

      {/* PROJECT GRID */}
      <section className="max-w-7xl mx-auto px-6 md:px-12 pb-24">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8 lg:gap-12">
          {projectsData.map((project, index) => (
            <ProjectCard
              key={index}
              image={project.image}
              title={project.title}
              onClick={() => setSelectedProject(project)}
            />
          ))}
        </div>
      </section>

      {/* MODAL POPUP */}
      {selectedProject && (
        <ProjectModal
          project={selectedProject}
          onClose={() => setSelectedProject(null)}
        />
      )}
    </main>
  );
};

/* =====================
  PROJECT CARD
===================== */
const ProjectCard = ({ image, title, onClick }: { image: string; title: string; onClick: () => void }) => {
  return (
    <div
      onClick={onClick}
      className={`
        cursor-pointer group relative w-full aspect-video rounded-xl 
        bg-[#12011a] border border-white/10 overflow-hidden
        transition-all duration-500 hover:border-purple-500/50 hover:shadow-[0_0_30px_rgba(168,85,247,0.15)]
      `}
    >
      {/* Background Image with fallback handling */}
      <div 
        className="absolute inset-0 bg-cover bg-center transition-transform duration-700 group-hover:scale-110"
        style={{ backgroundImage: `url('${image}')` }}
      />
      
      {/* Overlay Gradient */}
      <div className="absolute inset-0 bg-gradient-to-t from-black/90 via-black/20 to-transparent" />

      {/* Text Info */}
      <div className="absolute inset-0 flex items-end p-6">
        <h3 className="text-lg md:text-xl font-medium tracking-wide group-hover:text-purple-300 transition-colors">
          {title}
        </h3>
      </div>
    </div>
  );
};
/* =====================
  PROJECT MODAL
===================== */
const ProjectModal = ({ project, onClose }: { project: Project; onClose: () => void }) => {
  return (
    <div 
      className="fixed inset-0 z-50 flex items-center justify-center p-4 sm:p-6 bg-black/80 backdrop-blur-sm transition-opacity" 
      onClick={onClose}
    >
      {/* Modal Container */}
      <div 
        className="relative w-full max-w-3xl bg-[#12011a] border border-white/10 rounded-2xl overflow-hidden shadow-[0_0_40px_rgba(168,85,247,0.2)] flex flex-col max-h-[90vh]"
        onClick={(e) => e.stopPropagation()} 
      >
        {/* Close Button */}
        <button 
          onClick={onClose}
          className="absolute top-4 right-4 z-20 p-2 bg-black/50 hover:bg-black/80 rounded-full text-white/70 hover:text-white transition-all border border-white/10"
        >
          <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" viewBox="0 0 16 16">
            <path d="M2.146 2.854a.5.5 0 1 1 .708-.708L8 7.293l5.146-5.147a.5.5 0 0 1 .708.708L8.707 8l5.147 5.146a.5.5 0 0 1-.708.708L8 8.707l-5.146 5.147a.5.5 0 0 1-.708-.708L7.293 8 2.146 2.854Z"/>
          </svg>
        </button>

        {/* Modal Header: Conditionally Render 3D Viewer OR Static Image */}
        {project.modelPath ? (
          <div className="relative w-full h-64 sm:h-80 border-b border-white/10">
            <div className="absolute top-4 left-4 z-10 px-3 py-1 bg-black/50 backdrop-blur-md rounded-full text-xs font-medium text-white/80 border border-white/10 pointer-events-none">
              Click & Drag to Rotate
            </div>
            <ModelViewer modelPath={project.modelPath} />
          </div>
        ) : (
          <div 
            className="w-full h-56 sm:h-72 bg-cover bg-center border-b border-white/10"
            style={{ backgroundImage: `url('${project.image}')` }}
          />
        )}

        {/* Modal Content */}
        <div className="p-6 sm:p-8 overflow-y-auto">
          <h2 className="text-2xl sm:text-3xl font-bold tracking-wide mb-4 text-purple-300">
            {project.title}
          </h2>
          
          <p className="text-gray-300 leading-relaxed mb-8 text-sm sm:text-base opacity-90">
            {project.description}
          </p>

          {/* Action Buttons */}
          <div className="flex flex-wrap gap-4">
            {project.deployedLink && (
              <a 
                href={project.deployedLink} 
                target="_blank" 
                rel="noopener noreferrer"
                className="flex items-center gap-3 px-5 py-2.5 bg-purple-600/20 hover:bg-purple-600/40 border border-purple-500/30 rounded-lg transition-all text-sm font-medium tracking-wide"
              >
                <img src="/code.svg" alt="Code Icon" className="w-5 h-5" />
                View Live Project
              </a>
            )}
            
            {project.githubLink && (
              <a 
                href={project.githubLink} 
                target="_blank" 
                rel="noopener noreferrer"
                className="flex items-center gap-3 px-5 py-2.5 bg-white/5 hover:bg-white/10 border border-white/10 rounded-lg transition-all text-sm font-medium tracking-wide"
              >
                <img src="/github.svg" alt="GitHub Icon" className="w-5 h-5 opacity-90" />
                View on GitHub
              </a>
            )}

            {/* NEW: Download 3D Model Button */}
            {project.modelPath && (
              <a 
                href={project.modelPath} 
                download
                className="flex items-center gap-3 px-5 py-2.5 bg-blue-600/20 hover:bg-blue-600/40 border border-blue-500/30 rounded-lg transition-all text-sm font-medium tracking-wide text-blue-100"
              >
                <img src="/downloadb.svg" alt="Download Icon" className="w-5 h-5" />
                Download Model
              </a>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};